# ==== OPTION FLAGS =========================================================================
commitEnabled=false
differenceEnabled=true
flagUsed=false
# ==== UBUNTU HARDENING =====================================================================
CRON_HARDENING=true
SSH_HARDENING=true
BANNER_HARDENING=true
PROCESS_HARDENING=true
BOOTLOADER_HARDENING=true
NETWORK_HARDENING=true
# =====
TIMESYNCd_HARDENING=false
CHRONY_HARDENING=false
KERNEL_HARDENING=false
UFW_HARDENING=false
NFTABLES_HARDENING=false
IPTABLES_HARDENING=false
APP_ARMOR=false
BOOT_LOADER_PASSWORD="Password123" # Replace with your desired password
SUDO_HARDENING=false
FILESYSTEM_INTEGRITY=false
LOG_HARDENING=false
AUDIT_HARDENING=false
# ==== APACHE HARDENING =====================================================================
TMP="tmp"
# ==== WINDOWS CLIENT HARDENING =============================================================
